Update numpy requirement for reinforcement_learning to be <2
Current version of the example requires `numpy<2` otherwise the following
error can be seen:
```
AttributeError: module 'numpy' has no attribute 'bool8'. Did you mean: 'bool'?
```

Signed-off-by: Dmitry Rogozhkin <dmitry.v.rogozhkin@intel.com>