snli/model.py: can run using Python 2.* (#145)
Python 2.* does not support ``out.view(*size, -1)''. Expand it to ``out.view(size[0], size[1], -1)''.

Traceback (most recent call last):
  File "train.py", line 9, in <module>
    from model import SNLIClassifier
  File "snli/model.py", line 13
    return out.view(*size, -1)
SyntaxError: only named arguments may follow *expression